#!/bin/bash
# Note that when you download this file from Google Drive, it has been transformed into a txt file. You will need to turn it back into a Unix Executable file in order for this to work.
# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

#   do_one inlist_all end_all.mod LOGS_all
do_one inlist_high_mass end_all.mod LOGS_all

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'


